### DISCUSSION TITLE
What should uniprot.geneIDfield be for NCBI Gene identifiers

### DISCUSSION THREAD

**Discussion by PkiwiBird** [SysBioChalmers/GECKO#369] [Q&A] [answered]
What should go in the model adapter in the field `obj.params.uniprot.geneIDfield `if the genes in the yaml model are NCBI genes and there are no gene names? Only NCBI gene ids are in the `- genes` and in the genes in the `gene_reaction_rule`.
The gecko3 article says to look under `Names and Taxonomy - Gene Names` of one of the proteins of the proteome, but I cannot find the NCBI gene ids there, e.g. [https://www.uniprot.org/uniprotkb/A0JNW5/entry](https://www.uniprot.org/uniprotkb/A0JNW5/entry)
The ecModelGEMAdapter.m contains the following fields:
```
obj.params.kegg.ID = 'hsa';
obj.params.kegg.geneID = 'NCBI-GeneID';
obj.params.uniprot.type = 'proteome';
obj.params.uniprot.ID = 'UP000005640';
```
Genes in yaml file:
```
...
- gene_reaction_rule: "1591"
...
- genes:
    - !!omap
      - id: "100"
    - !!omap
      - id: "10005"

```
