### ISSUE TITLE
store ec-model in yml format

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#178]
Currently, lossless export of ec-models can only be as .mat files, as SBML does not have fields to store many of the additional fields. The new `model.ec` structure would be even more problematic. However, it would be good to have a flat-text lossless file format for export and import of ec-models.

We can use YAML (expanding on RAVEN's [`writeYAMLmodel`](https://github.com/SysBioChalmers/RAVEN/blob/devel/io/writeYAMLmodel.m)), as we can easily define the additional fields, the I/O of the YML file is faster than libSBML, and the file format is very suitable for diff-ing.

Most of `model.ec` will be easy to implement, the only tricky part might be `rxnEnzMat`. Probably most sensible is to use a structure that is similar to how reaction stoichiometry is included in YML:

```yaml
    - !!omap
      - id: "r_0310"
      - name: "cystathionine g-lyase"
      - metabolites: !!omap
          - s_0178: 1
          - s_0419: 1
          - s_0803: -1
          - s_0980: -1
          - s_0981: 1
```
